onboarding = false
[theme]
name = "solarized-light"
auto_switch = false

[keys]
prefix = "ctrl+z"
previous_workspace = "prefix+ctrl+left"
next_workspace = "prefix+ctrl+right"
previous_agent = "prefix+ctrl+up"
next_agent = "prefix+ctrl+down"
previous_tab = ["prefix+p", "prefix+ctrl+p", "prefix+comma"]
next_tab = ["prefix+n", "prefix+ctrl+n", "prefix+."]

[[keys.command]]
key = "prefix+ctrl+w"
type = "pane"
command = "fish -c 'herdr_tabs_picker'"

[[keys.command]]
key = "ctrl+shift+w"
type = "pane"
command = "fish -c 'herdr_tabs_picker'"

[[keys.command]]
key = "prefix+ctrl+space"
type = "pane"
command = "fish -c 'herdr_shell_popup'"

[[keys.command]]
key = "prefix+ctrl+e"
type = "pane"
command = "fish -c 'herdr_yazi_files_picker'"

[experimental]
switch_ascii_input_source_in_prefix = false

[ui]
agent_panel_sort = "spaces"

[ui.toast]
delivery = "terminal"
