"$schema" = 'https://starship.rs/config-schema.json'

scan_timeout = 30
command_timeout = 200

[directory]
truncation_length = 2
truncate_to_repo = false
fish_style_pwd_dir_length = 1
read_only = " 󰌾"

[shell]
fish_indicator = "󰈺"
zsh_indicator = "󰰶"
bash_indicator = "\ue760"
powershell_indicator = ""
style = "cyan bold"
disabled = false

