# Prefix
set -g prefix C-z
bind C-z display-message ""

# Term
set -g default-terminal "$TERM"
set -ga terminal-overrides ",$TERM:Tc"

set -g allow-passthrough all
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# View
set -g history-limit 10000
set -g base-index 1
set -g repeat-time 1000

# Navigation
# act like vim
setw -g mode-keys vi
bind -r h select-pane -L \; refresh-client
bind -r j select-pane -D \; refresh-client
bind -r k select-pane -U \; refresh-client
bind -r l select-pane -R \; refresh-client
bind -r C-h select-pane -L \; refresh-client
bind -r C-j select-pane -D \; refresh-client
bind -r C-k select-pane -U \; refresh-client
bind -r C-l select-pane -R \; refresh-client
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind -r , select-window -t :-
bind -r . select-window -t :+
bind -r C-p select-window -t :-
bind -r C-n select-window -t :+

# Non-prefix window navigation
bind -n C-S-, previous-window
bind -n C-S-. next-window
bind -n C-S-w display-popup -E "fish -c 'fzf_tmux_windows_popup'"

# files
bind C-f run-shell "tmux set-buffer -b _fzf_parent_pane '#{pane_id}'" \; display-popup -d "#{pane_current_path}" -E -w 80% -h 80% "fish -c 'fzf_tmux_files_popup'"
bind C-g display-popup -d "#{pane_current_path}" -w 95% -h 90% "lazygit"
bind C-e run-shell "tmux set-buffer -b _yazi_parent_pane '#{pane_id}'" \; new-window -a -t '{end}' -n yazi -c "#{pane_current_path}" "fish -c 'yazi_tmux_files_picker'"

# Swap pane
bind N swap-pane -D
bind P swap-pane -U

# bind C-n swap-window -t:+ \; swap-pane -s:-
# bind C-p swap-window -t:- \; swap-pane -s:+

bind C-w choose-window

# Synchronize
bind C-s send-keys 'tmux set-window-option synchronize-panes '

# set window's title
unbind A
bind A command-prompt "rename-window %%"

# Splitting
unbind %
bind | split-window -hc "#{pane_current_path}"
bind - split-window -vc "#{pane_current_path}"

# New-window
set -g renumber-windows on
bind 'c' new-window -c "#{pane_current_path}"

# Mouse
set -g mouse on
bind-key -n WheelUpPane if-shell -Ft= "#{?pane_in_mode,1,#{alternate_on}}" "send-keys -M" "copy-mode"

set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_show_sync_mode 'on'

TMUX_PLUGIN_MANAGER_PATH="~/.local/share/tmux/plugins"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-urlview'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'vaaleyard/tmux-dotbar'
set -g @fzf-url-bind 'C-x'
set -g @tmux-dotbar-maximized-icon " 󰊓"
set -g @tmux-dotbar-window-status-format "#{b:pane_current_path}"
set -g @tmux-dotbar-window-status-current-format "#{b:pane_current_path}"

if -F '#{==:#{E:TMUX_THEME},light}' 'source-file ~/.config/tmux/themes/light.conf' 'source-file ~/.config/tmux/themes/dark.conf'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-nvim 'session'

run "${TMUX_PLUGIN_MANAGER_PATH}/tpm/tpm"
