set -g @tmux-dotbar-bg "#181616"
set -g @tmux-dotbar-fg "#625e5a"
set -g @tmux-dotbar-fg-current "#c5c9c5"
set -g @tmux-dotbar-fg-session "#9e9b93"
set -g @tmux-dotbar-fg-prefix "#8ba4b0"

set -g status-style "bg=#181616,fg=#625e5a"
set -g message-style "bg=#e6c384,fg=#181616"
set -g message-command-style "bg=#181616,fg=#e6c384"

setw -g mode-style "bg=#e6c384,fg=#181616"
setw -g menu-style "bg=#181616,fg=#c5c9c5"
setw -g menu-selected-style "bg=#8ba4b0,fg=#181616"
setw -g pane-border-style "fg=#625e5a"
setw -g pane-active-border-style "fg=#8ba4b0"
setw -g window-status-style "bg=#181616,fg=#625e5a"
setw -g window-status-current-style "bg=#181616,fg=#c5c9c5"
setw -g window-status-activity-style "bg=#c5c9c5,fg=#181616"
setw -g window-status-bell-style "bg=#8ba4b0,fg=#181616,bold"
