set -g @tmux-dotbar-bg "#fffcf0"
set -g @tmux-dotbar-fg "#878580"
set -g @tmux-dotbar-fg-current "#100f0f"
set -g @tmux-dotbar-fg-session "#575653"
set -g @tmux-dotbar-fg-prefix "#205ea6"

set -g status-style "bg=#fffcf0,fg=#878580"
set -g message-style "bg=#205ea6,fg=#fffcf0"
set -g message-command-style "bg=#fffcf0,fg=#205ea6"

setw -g mode-style "bg=#e6e4d9,fg=#100f0f"
setw -g menu-style "bg=#fffcf0,fg=#100f0f"
setw -g menu-selected-style "bg=#205ea6,fg=#fffcf0"
setw -g pane-border-style "fg=#cecdc3"
setw -g pane-active-border-style "fg=#205ea6"
setw -g window-status-style "bg=#fffcf0,fg=#878580"
setw -g window-status-current-style "bg=#fffcf0,fg=#100f0f"
setw -g window-status-activity-style "bg=#e6e4d9,fg=#100f0f"
setw -g window-status-bell-style "bg=#af3029,fg=#fffcf0,bold"
