name: Renovate

on:
  schedule:
    - cron: "17 18 * * 0"
  workflow_dispatch:

permissions:
  contents: read

env:
  RENOVATE_GIT_AUTHOR: hnagato <134620+hnagato@users.noreply.github.com>
  RENOVATE_GIT_PRIVATE_KEY: ${{ secrets.RENOVATE_GIT_PRIVATE_KEY }}
  RENOVATE_REPOSITORIES: hnagato/dotfiles

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Run Renovate
        uses: renovatebot/github-action@v46.1.14
        with:
          # renovate: datasource=docker depName=ghcr.io/renovatebot/renovate
          renovate-version: 43.181.0
          token: ${{ secrets.RENOVATE_TOKEN }}
