legacy_version_file = true
legacy_version_file_disable_tools = ['python']

always_keep_download = false
always_keep_install = false

plugin_autoupdate_last_check_duration = '1 week'

trusted_config_paths = ['~/projects']

verbose = false
